### ISSUE TITLE
P1 gen2 ME Update failes

### ISSUE THREAD

**Issue by agurenko** [fwupd/firmware-lenovo#251] opened 2022-08-04 15:41 UTC
As continuation of https://github.com/fwupd/firmware-lenovo/issues/224#issuecomment-1205378202:

-     fwupdmgr update --show-all

```
fwupdmgr update --show-all
Devices with no available firmware updates: 
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI dbx
Devices with the latest available firmware version:
 • Embedded Controller
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Intel Management Engine from 192.72.1757 to 192.90.2072?             ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Lenovo ThinkPad P1 Gen2 X1 Extreme 2nd Corporate (Consumer) ME Firmware      ║
║                                                                              ║
║ 20QUS10L16 must remain plugged into a power source for the duration of the   ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]:
```

-     system firmware version and Intel Management Engine firmware version in BIOS main page

  - ME: 12.0.90.2072
  - BIOS: N20ET56W (1.43)

-     OS and fwupdmgr version
  - OS: Fedora Linux 36 KDE Spin; kernel 5.19.0-65.fc37.x86_64
  - fwupd-1.8.3-1.fc36.x86_64

**Comment by ChiWei-Chen** [comment] 2022-08-10 08:37
@agurenko , thanks, this seems to be related to other ME version issue #224 need to be fixed in the BIOS update, I'll keep you update if there is any progress from FW team. (LO-1938 for my tracking)

**Comment by agurenko** [comment] 2022-08-10 08:59
> @agurenko , thanks, this seems to be related to other ME version issue #224 need to be fixed in the BIOS update, I'll keep you update if there is any progress from FW team. (LO-1938 for my tracking)

Perfect, thank you

**Comment by ChiWei-Chen** [comment] 2022-08-30 15:44
@agurenko , FW already merged the fix in the next BIOS release, I'll keep you update once there is clear ETA.

**Comment by agurenko** [comment] 2022-08-30 17:11
Perfect, thank you. Ready to test it as soon as it's released

**Comment by agurenko** [comment] 2022-09-05 17:33
> @agurenko , FW already merged the fix in the next BIOS release, I'll keep you update once there is clear ETA.

I see there is a new BIOS 1.44 from 1st of September available now on Lenovo support site. Is that the one?

**Comment by ChiWei-Chen** [comment] 2022-09-20 13:21
@agurenko sorry for the late, FW team replied that 1.44 has not included the fix yet, we'll keep you update once we have ETA of next release.

**Comment by agurenko** [comment] 2022-09-20 13:23
> @agurenko sorry for the late, FW team replied that 1.44 has not included the fix yet, we'll keep you update once we have ETA of next release.

Yeah, no worries, I've tried this update and it didn't solve the problem, so I figured :) I'll be on a lookout for a new release. Thank you for the follow up, really appreciate the effort here.

**Comment by agurenko** [comment] 2022-11-17 14:23
> @agurenko sorry for the late, FW team replied that 1.44 has not included the fix yet, we'll keep you update once we have ETA of next release.

I've tried the latest 1.45 update from 14 November and looks like it fixed the problem, no reoccurring update and the reported version match. Can you please confirm that was the target release?

**Comment by agurenko** [comment] 2022-11-17 14:24
Oh, actually nevermind, it's clearly mentioned in a changelog:

```
CHANGES IN THIS RELEASE
  Version 1.45
[...]
[Problem fixes]
- Fixed an issue where an incorrect Intel Management Engine firmware version might be
  returned at capsule update under Linux.
```

**Comment by ChiWei-Chen** [comment] 2022-11-18 03:10
@agurenko , thanks, it's great to know the problem is resolved on your system.

**Closed as completed by ChiWei-Chen** 2022-11-18 03:10 UTC

**Comment by unoexperto** [comment] 2022-11-18 09:57
@ChiWei-Chen 

I don't see 1.45 for ThinkPad P1 Gen 1, X1 Extreme Gen 1 here

https://pcsupport.lenovo.com/gb/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-extreme/downloads/ds504956-bios-update-utility-bootable-cd-for-windows-10-64-bit-and-linux-thinkpad-p1-x1-extreme?category=BIOS%2FUEFI

Is it going to be published ?

**Comment by agurenko** [comment] 2022-11-18 12:30
> @ChiWei-Chen
> 
> I don't see 1.45 for ThinkPad P1 Gen 1, X1 Extreme Gen 1 here
> 
> https://pcsupport.lenovo.com/gb/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-extreme/downloads/ds504956-bios-update-utility-bootable-cd-for-windows-10-64-bit-and-linux-thinkpad-p1-x1-extreme?category=BIOS%2FUEFI
> 
> Is it going to be published ?

gen1 and gen2 are different machines, you might need to open a separate issue to track it like I did

**Comment by seichter** [comment] 2022-11-18 14:02
Can confirm the update to 1.45 fixes the Intel ME problem for the P1Gen2 - however, I had to force it to update the database with `fwupdmgr refresh`

**Comment by kmauleon** [comment] 2022-11-21 01:40
hi @seichter great!  you just did what is expected.... thank you very much!

**Comment by ChiWei-Chen** [comment] 2022-11-22 05:10
@unoexperto 
The issue for ThinkPad P1 Gen 1, X1 Extreme Gen 1 is tracked in #248, it could be available these 2 weeks.
