### ISSUE TITLE
2x T14 Gen 2 dead on 1.5.X UEFI branch

### ISSUE THREAD

**Issue by savchenko** [fwupd/firmware-lenovo#337] opened 2023-05-08 13:27 UTC
A bit of a history:

1. T14 Gen 2 is updated to v1.55 BIOS image.
2. After the update, device refuses to boot _anything_ including the Lenovo Diagnostics EFI.
   Settings can be entered and asset information accessed.
4. Reset to factory defaults does not help. Device goes back to Lenovo for the system board replacement. 
5. Device is received with the new system board and, strangely, different NVMe drive.

Exactly two actions were performed on the repaired device:

1. Wiped the NVMe using ThinkShield Secure Wipe launched from the UEFI menu.
2. Reset BIOS settings to factory default.

The laptop enters the same unresponsive state where an attempt to boot anything (PXE, USB, on/off Secure Boot, etc) results in a black screen with backlight on.

I have reported it via normal support channel, however I suspect this might warrant an attention of the firmware team. This particular device had no issues updating from very early versions (CTO order right after the release) till v1.4X branch. v1.5X appears to be cursed.

Ping @mrhpearson

**Comment by romanchyla** [comment] 2023-06-16 21:20
I seem to have hit the same issue. My laptop went black today - during work. I tried to reset, remove battery....after many hours, left it charging, it suddenly woke up -- presented Lenovo screen, I was able to enter BIOS (version was 1.55) then I booted into the OS (ubuntu) was going through the logs to see what has happened before the freeze --  while doing it, the laptop froze again.... before that, I only saw in the logs that fwupdate tried to download packages (something small ~217KB) and that fwupdatemgr ran

also possibly related: https://github.com/fwupd/firmware-lenovo/issues/348 

right now my laptop is dead: I'm waiting if the charging brings it up

**Comment by hughsie** [comment] 2023-06-17 12:46
> My laptop went black today

Why do you think this is because of firmware updates? It sounds like a different set of symptoms.

**Comment by savchenko** [comment] 2023-06-17 14:02
> right now my laptop is dead: I'm waiting if the charging brings it up

If this succeeds, then the root problem is indeed a different one. My case has warranted M/B replacement. I have asked technician if they can attach a POMONA clip and re-flash it on the spot, but was told it's not that simple as there are more moving parts than a single EEPROM chip.

**Comment by romanchyla** [comment] 2023-06-17 14:33
> Why do you think this is because of firmware updates? It sounds like a different set of symptoms.

So yes, it is a hypothesis - I can't be sure. But the coincidence is strange:

- Lenovo released a new firmware on June 15
- my laptop died June 16 (morning)
- logs reveal fwupd was running (and apt fetched 217KB from a private repo)

---

Here is what I think happened. I have flashed BIOS 1.55 myself several months prior -- and used the laptop without problems.

On June 15, new firmware was released by Lenovo. I have Ubuntu and my employer (Amazon) installs updates automatically. My **conjecture** is this: I logged in in the morning, the apt discovered new firmware, downloaded the latest firmware (and perhaps even installed it; at least wrote it somewhere where it would be picked up during boot)

While I worked, the laptop screen went black - with backlight present - roughly 30mins after opening the laptop.

When black, after two minutes, I restarted it. It was blank -- after several minutes I rebooted it again. All that time without the laptop being plugged into a charger. Unknowingly, I have probably interrupted the flashing -- https://github.com/fwupd/firmware-lenovo/issues/348

It now has all the symptoms of a broken BIOS - it turns on, screen is blank. No BIOS. No HDMI output.

I removed the battery. Did hard reset. Left the laptop in the charger. Suddenly, after ~3h I got the Lenovo boot (this is super weird; no idea) - I went to bios, it had version 1.55. I was able to boot. Then I started looking into the logs - I saw that roughly 15minutes before the crash, fwupd downloaded 217KB -- but also, that it failed several times -- I didn't have a security token refreshed and we are using private repositories. 

While I was trying to sift through the logs; the laptop froze -- not a black screen but the latest image -- idiot as I am I had not realized it might try to repeat the same actions and that I should have tried to stop any update process (at that point I only discovered fwupd)

charging din't make a difference, the laptop is in coma now

**Comment by mrhpearson** [comment] 2023-06-19 14:30
Firstly apologies to @savchenko for the original post - I had completely missed that. Let me know if you got back to stable HW with everything working. As a quick note - 'OS optimised' default settings are recommended (and then disable secure boot if you don't want it) The regular default settings are, in my opinion, peculiar and not recommended for either Linux or Windows.

@romanchyla - afraid I don't have any particular insight, but I've created internal ticket LO-2520 asking the FW team to review. If your system does magically boot again then can you get the output from 'fwupdmgr get-history' and 'fwupdmgr get-device' so that we can see what FW was updated and when please.

**Comment by savchenko** [comment] 2023-07-05 15:08
@mrhpearson, stability achieved on 2nd replaced motherboard. The 1st replacement has died in exactly the same manner.

**Comment by savchenko** [comment] 2023-07-30 11:05
Re-opening as this has happened again when updating from v1.55 to v1.56.

@mrhpearson , can I e-mail you additional details?

**Comment by hughsie** [comment] 2023-07-31 08:29
@mrhpearson is on PTO this week, I'm sure he'll get back to you next week.

**Comment by savchenko** [comment] 2023-08-07 11:28
@mrhpearson , apologies for bumping this up again, but are you back by any chance?

Or, maybe @ChiWei-Chen can help? Lenovo support gave us (it's a business laptop) the cold shoulder.

**Comment by mrhpearson** [comment] 2023-08-09 18:46
Back from PTO - but @ChiWei-Chen, can you review this with the FW team. I'll re-open LO-2520

I know it's not hugely helpful - but this platform looks like it has had 23k successful downloads so the suspicion is still unfortunately on HW but I'm not sure what is going on with your system that the issue went away with a MB replacement but is back again...that's super weird.

 - I assume not booting a USB stick with Fedora/Ubuntu on it.
 - Have you tried the pinhole reset on the back? 
 - Just to confirm - you haven't done anything with the system keys/certificates have you? (previous reports of users manipulating secure boot keys from Linux utilities and causing issues...bit of a long shot)

Mark

**Comment by savchenko** [comment] 2023-08-10 03:22
@mrhpearson, glad to see that you're back and following-up on the bug #209943 at kernel.org :)

- Update was performed from USB stick that had `n34ur23w.iso` copied to it (`dd`).
- Yes, many times, with and without disconnecting the main and RTC batteries.
- No. This particular laptop has the default set of `PK/KEK/DB/DBX`.

**To summarise:** I can enter the BIOS settings and change any property, changes are saved. Attempting to load EFI application from either USB or NVMe results in a black screen with backlight turned on. The only change observed is the <kbd>Esc</kbd> LED goes off after few seconds.

Loading "Lenovo Diagnostics" from the boot menu fails in the same manner.

**Comment by mrhpearson** [comment] 2023-08-10 17:54
Ack. Details have been forwarded to the FW team - will let you know when we hear back.

**Comment by ChiWei-Chen** [comment] 2023-08-14 11:09
@savchenko , I just got a question from FW team, do you have any information about the BIOS ROM? Thanks!

> I noticed that the customer's motherboard has been changed, did customer also replace the BIOS ROM with another BIOS bin file(not original BIOS bin file)? Or did customer still use original BIOS ROM with original BIOS bin file?

**Comment by savchenko** [comment] 2023-08-14 12:39
@ChiWei-Chen

Sorry, not quite following. The motherboard was replaced by Lenovo. The update was installed from ISO file `dd`'d onto USB stick:
```
n34ur23w.iso
SHA256: F4EC38C6F00939F056F44D7003C9DB36DFF0105E273EB962D5EBA3158BAF5439
```
I have not modified the ISO in any way, nor I have observed a warning or an error during the update process.

**Comment by ChiWei-Chen** [comment] 2023-08-15 05:40
@savchenko thanks, the FW team wants to know did you try load default BIOS setting with following instructions this time?

> entering in BIOS setup by press “F1”, then press “F9” to load BIOS default, then press “F10” to save change first.(F1->F9->F10)

**Comment by savchenko** [comment] 2023-08-16 05:42
@ChiWei-Chen , I have tried loading default settings, but always with mouse. Entered BIOS settings via boot menu (F12) or F1. Additionally, I have tried with and without "System optimised defaults" toggle.

**Comment by ChiWei-Chen** [comment] 2023-08-16 06:36
@savchenko , thanks for the feedback, I'll share this with the team.

**Comment by ChiWei-Chen** [comment] 2023-08-17 04:41
hi 
@savchenko the team suggested contacting customer support again.
Since they cannot reproduce the same problem and suspect the data in the BIOS ROM may be lost due to unexpected updating operations, the lost data cannot be restored by upgrading the BIOS.
So, it is suggested to burn a new BIOS bin file in BIOS ROM. But only customer service can do that for you.

Just want to double-confirm, is BIOS upgraded to 1.56 already?

Thanks.

**Comment by mrhpearson** [comment] 2023-09-08 13:33
Closing ticket

**Closed as completed by mrhpearson** 2023-09-08 13:33 UTC

**Comment by savchenko** [comment] 2023-09-09 03:11
@ChiWei-Chen , the device will be returned to Lenovo for incineration. After replacing the system board it has entered a peculiar state where any attempt to update BIOS would fail with `ERROR 215 - Failed to read BIOS from memory! Status = 9`:

![image](https://github.com/fwupd/firmware-lenovo/assets/300146/988537fa-a9ea-4634-9bfc-0641187434ca)

Mind you, it's a freshly unpacked laptop with Windows 11 installed and BIOS update was initiated from "Lenovo Update" application.

Number of hours spent on this particular unit is now well in excess of its cost... Burn it, it's cursed.

@mrhpearson , please don't re-open the ticket.
